name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ma_base
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pytest

  deploy:
  needs: tests
  if: github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}

      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        git clone https://ManouDig:$HF_TOKEN@huggingface.co/spaces/ManouDig/consommation hf-space

        rsync -av --delete \
          --exclude ".git" \
          ./ hf-space/

        cd hf-space

        git add .

        git commit -m "Automatic deployment" || true

        git push