name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - "feature/**"

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pytest

  deploy:
    needs: tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://ManouDig:$HF_TOKEN@huggingface.co/spaces/ManouDig/consommation hf-space

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "hf-space" \
            --exclude "data/model.pkl" \
            ./ hf-space/

          cd hf-space

          git add .
          git commit -m "Automatic deployment from GitHub Actions" || echo "Nothing to commit"
          git push